name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Ensure the dist directory exists
      - name: Create dist directory
        run: mkdir -p dist

      # Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: JoaoVDonato
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Commit and push changes to main
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
